"""Render the graph store into Obsidian notes, and read hand-written notes back in."""
import os
import re
import shutil

from . import yamlish
from .store import RELATIONS
from .util import VAULT_DIR, log, norm_name, safe_filename, today

START = "<!-- HOOT:AUTO:START (regenerated by HOOT; write your own notes outside this block) -->"
END = "<!-- HOOT:AUTO:END -->"
FOLDERS = {"person": "People", "organization": "Organizations", "work": "Works", "grant": "Grants"}
ENTITY_MANAGED = {"hoot", "type", "name", "canonical_id", "ids", "aliases", "updated", "attributes"}
SCALAR_ATTRS = ["industry", "sic", "state_of_incorporation", "tickers", "jurisdiction", "country", "city",
                "legal_form", "entity_status", "publication_date", "venue", "work_type", "is_retracted",
                "cited_by_count", "institution_type", "is_funder", "title", "project_start", "project_end",
                "blurb", "website", "direct_parent_exception", "ultimate_parent_exception"]
LINK_ATTRS = ["sec_profile_url", "lei_record_url", "openalex_url", "littlesis_url", "reporter_url"]


class Renderer:
    def __init__(self, store, cfg):
        self.s = store
        self.root = cfg.get("notes_folder", "HOOT")
        self.abs = lambda rel: os.path.join(VAULT_DIR, rel.replace("/", os.sep))

    # ---------------------------------------------------------- paths & links
    def entity_path(self, e):
        if e["note_path"]:
            return e["note_path"]
        folder = f"{self.root}/{FOLDERS.get(e['type'], 'Other')}"
        base = safe_filename(e["name"])
        taken = {os.path.basename(r[0])[:-3].lower() for r in
                 self.s.db.execute("SELECT note_path FROM entities WHERE note_path IS NOT NULL AND id<>?", (e["id"],))}
        cand, n = base, 2
        while cand.lower() in taken or (os.path.exists(self.abs(f"{folder}/{cand}.md")) and not self._owned(f"{folder}/{cand}.md", e)):
            cand = f"{base} ({n})"
            n += 1
        path = f"{folder}/{cand}.md"
        self.s.db.execute("UPDATE entities SET note_path=? WHERE id=?", (path, e["id"]))
        e["note_path"] = path
        return path

    def _owned(self, rel, e):
        fm, _ = yamlish.split(open(self.abs(rel), encoding="utf-8").read())
        return fm.get("canonical_id") == e["canonical_id"]

    def link(self, eid, label=None):
        e = self.s.entity(eid)
        if not e:
            return "?"
        p = self.entity_path(e)[:-3]
        return f"[[{p}|{(label or e['name']).replace('|', '/').replace(']', ')')}]]"

    def edge_path(self, ed):
        if ed["note_path"]:
            return ed["note_path"]
        a, b = self.s.entity(ed["src"]), self.s.entity(ed["dst"])
        name = safe_filename(f"{a['name'][:50]} → {ed['relation']} → {b['name'][:50]} {ed['id'][-5:]}", 160)
        path = f"{self.root}/Edges/{name}.md"
        self.s.db.execute("UPDATE edges SET note_path=? WHERE id=?", (path, ed["id"]))
        ed["note_path"] = path
        return path

    # ---------------------------------------------------------- io
    def _read(self, rel):
        p = self.abs(rel)
        if not os.path.exists(p):
            return None
        with open(p, encoding="utf-8") as f:
            return f.read()

    def _write(self, rel, text):
        p = self.abs(rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        old = self._read(rel)
        if old == text:
            return False
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        return True

    @staticmethod
    def _user_parts(body):
        """(text before auto block minus our H1, text after auto block)"""
        if START in body and END in body:
            before, rest = body.split(START, 1)
            after = rest.split(END, 1)[1]
            before = re.sub(r"\A\s*# .*\n?", "", before, count=1)
            return before.strip("\n"), after.lstrip("\n")
        return "", body.strip("\n")

    # ---------------------------------------------------------- entity notes
    def _dates(self, ed):
        if ed["start_date"] or ed["end_date"]:
            end = ed["end_date"] or ("present" if ed["is_current"] != 0 else "?")
            return f"{ed['start_date'] or '?'} → {end}"
        if ed["first_seen"]:
            span = ed["first_seen"] if ed["first_seen"] == ed["last_seen"] else f"{ed['first_seen']} → {ed['last_seen']}"
            n = len(ed["attrs"].get("evidence", []))
            return f"in filings {span}" + (f" ({n} docs)" if n > 1 else "")
        return ""

    def _edge_line(self, ed, eid):
        out = ed["src"] == eid
        other = self.link(ed["dst"] if out else ed["src"])
        rel = f"**{ed['relation']}**" + (f" ({ed['qualifier']})" if ed["qualifier"] else "")
        bits = [f"→ {rel} {other}" if out else f"← {other} {rel}"]
        if ed["percent"] is not None:
            bits.append(f"{ed['percent']:g}% of class")
        if ed["amount"]:
            bits.append(f"{ed['currency'] or ''} {ed['amount']:,.0f}".strip())
        d = self._dates(ed)
        if d:
            bits.append(d)
        if ed["is_current"] == 0 or (ed["end_date"] and ed["end_date"] < today()):
            bits.append("*former*")
        bits.append(f"w={ed['conflict_weight']}")
        if ed["evidence_url"]:
            bits.append(f"[{ed['source'] or 'source'}]({ed['evidence_url']})")
        elif ed["source"]:
            bits.append(ed["source"])
        bits.append(f"[[{self.edge_path(ed)[:-3]}|ⓘ]]")
        return "- " + " · ".join(bits)

    def render_entity(self, eid):
        e = self.s.entity(eid)
        if not e:
            return
        path = self.entity_path(e)
        old = self._read(path) or ""
        fm_old, body_old = yamlish.split(old)
        before, after = self._user_parts(body_old) if old else ("", "## Investigator notes\n\n")
        a = e["attrs"]

        fm = {"hoot": "entity", "type": e["type"], "name": e["name"], "canonical_id": e["canonical_id"],
              "ids": e["ids"], "aliases": e["aliases"]}
        for k in SCALAR_ATTRS:
            v = a.get(k)
            if v not in (None, "", []):
                fm[k] = v if not isinstance(v, list) else [x for x in v if x is not None]
        fm["updated"] = today()
        tags = fm_old.get("tags") or []
        tags = [tags] if isinstance(tags, str) else list(tags)
        if f"hoot/{e['type']}" not in tags:
            tags.append(f"hoot/{e['type']}")
        user = {k: v for k, v in fm_old.items() if k not in ENTITY_MANAGED and k not in fm and k != "tags"}
        user.setdefault("domain", [])
        fm.update(user)
        fm["tags"] = tags

        lines = [f"# {e['name']}", "", START, ""]
        idl = [f"`{s}`: {v}" for s, v in sorted(e["ids"].items())]
        links = [f"[{k.replace('_url', '').replace('_', ' ')}]({a[k]})" for k in LINK_ATTRS if a.get(k)]
        lines += ["> [!abstract] Identity", f"> **canonical_id:** `{e['canonical_id']}`  ", "> " + " · ".join(idl)]
        if links:
            lines.append("> " + " · ".join(links))
        if a.get("merged_from"):
            lines.append("> merged from: " + ", ".join(f"`{m}`" for m in a["merged_from"]))
        lines.append("")

        for k in ("direct_parent_exception", "ultimate_parent_exception"):
            if a.get(k):
                lines += [f"> [!warning] GLEIF: {k.split('_')[0]} parent not reported: **{a[k]}**", ""]
        if a.get("opensanctions_candidates"):
            lines += ["> [!danger] OpenSanctions name matches (unverified)"]
            lines += [f"> - [{h['caption']}]({h['url']}): {', '.join(h['topics']) or 'no topics'} (score {h['score']})"
                      for h in a["opensanctions_candidates"]]
            lines.append("")

        edges = self.s.edges_of(eid)
        hard = [x for x in edges if x["control"] == "hard"]
        soft = [x for x in edges if x["control"] != "hard"]
        key = lambda x: (-(x["is_current"] if x["is_current"] is not None else 1), -x["conflict_weight"], x["relation"])
        lines.append(f"## Connections ({len(edges)})")
        for title, group in (("Hard structural control", hard), ("Soft influence", soft)):
            if group:
                lines += ["", f"### {title} ({len(group)})"]
                lines += [self._edge_line(x, eid) for x in sorted(group, key=key)]
        lines.append("")

        if a.get("key_filings"):
            lines += ["## Key filings"] + [f"- {k['date']} **{k['form']}**: [{k['url'].rsplit('/', 1)[-1]}]({k['url']})"
                                            for k in a["key_filings"]] + [""]
        if a.get("award_by_fiscal_year"):
            lines += ["## Award by fiscal year"] + [f"- FY{fy}: ${amt:,.0f}" for fy, amt in sorted(a["award_by_fiscal_year"].items())] + [""]
        lines += [END, ""]
        text = yamlish.dump(fm) + "\n".join(lines) + ("\n" + before + "\n" if before else "") + "\n" + after
        self._write(path, text.rstrip("\n") + "\n")

    # ---------------------------------------------------------- edge notes
    def render_edge(self, ed):
        path = self.edge_path(ed)
        old = self._read(path) or ""
        fm_old, body_old = yamlish.split(old)
        _, after = self._user_parts(body_old) if old else ("", "## Notes\n\n")
        a, b = self.s.entity(ed["src"]), self.s.entity(ed["dst"])
        fm = {"hoot": "edge", "edge_id": ed["id"], "origin": ed["origin"], "relation": ed["relation"],
              "control": ed["control"], "conflict_weight": ed["conflict_weight"],
              "from": self.link(ed["src"]), "to": self.link(ed["dst"]),
              "from_id": a["canonical_id"], "to_id": b["canonical_id"]}
        for k in ("qualifier", "start_date", "end_date", "is_current", "percent", "amount", "currency",
                  "source", "evidence_url", "filing_date", "first_seen", "last_seen", "date_verified",
                  "source_sha256", "verification_hash"):
            if ed[k] is not None:
                fm[k] = bool(ed[k]) if k == "is_current" else ed[k]
        fm["domain"] = fm_old.get("domain", [])
        fm["tags"] = [f"hoot/edge", f"hoot/{ed['control']}"]
        ev = ed["attrs"].get("evidence", [])
        lines = [START, "", f"{self.link(ed['src'])} **{ed['relation']}** {self.link(ed['dst'])}", ""]
        if ev:
            lines += [f"### Evidence trail ({len(ev)})"] + [
                f"- {x.get('date') or 'undated'}: [{x['url'].rstrip('/').rsplit('/', 1)[-1]}]({x['url']})" + (f" · sha256 `{x['sha256'][:16]}…`" if x.get("sha256") else "")
                for x in ev] + [""]
        extra = {k: v for k, v in ed["attrs"].items() if k != "evidence" and v not in (None, "", [], {})}
        if extra:
            lines += ["### Source detail"] + [f"- **{k}**: {v}" for k, v in extra.items()] + [""]
        lines += [END, ""]
        self._write(path, yamlish.dump(fm) + "\n".join(lines) + "\n" + after.rstrip("\n") + "\n")

    # ---------------------------------------------------------- orchestration
    def render(self, all_=False):
        ids = [r[0] for r in self.s.db.execute("SELECT id FROM entities")] if all_ else sorted(self.s.touched)
        edge_ids = set()
        for eid in ids:
            for ed in self.s.edges_of(eid):
                edge_ids.add(ed["id"])
        for eid in ids:
            self.render_entity(eid)
        for ed in self.s.edges("1=1"):
            if ed["id"] in edge_ids:
                self.render_edge(ed)
        self.prune()
        self.s.touched.clear()
        self.s.commit()
        log(f"rendered {len(ids)} entity notes, {len(edge_ids)} edge notes")

    def prune(self):
        """Move notes HOOT no longer backs (e.g. after a merge) into _Archive instead of deleting them."""
        live = {r[0] for r in self.s.db.execute("SELECT note_path FROM entities WHERE note_path IS NOT NULL")}
        live |= {r[0] for r in self.s.db.execute("SELECT note_path FROM edges WHERE note_path IS NOT NULL")}
        base = self.abs(self.root)
        for folder in list(FOLDERS.values()) + ["Edges", "Other"]:
            d = os.path.join(base, folder)
            if not os.path.isdir(d):
                continue
            for fn in os.listdir(d):
                if not fn.endswith(".md"):
                    continue
                rel = f"{self.root}/{folder}/{fn}"
                if rel in live:
                    continue
                fm, body = yamlish.split(self._read(rel) or "")
                if fm.get("hoot") in ("entity", "edge") and fm.get("origin", "auto") != "manual" and \
                        (fm.get("hoot") == "entity" or fm.get("edge_id")):
                    before, after = self._user_parts(body)
                    user_text = (before + after).replace("## Investigator notes", "").replace("## Notes", "").strip()
                    if not user_text and not fm.get("domain"):
                        os.remove(self.abs(rel))          # pure generated note, nothing of yours in it
                        continue
                    dst = self.abs(f"{self.root}/_Archive/{folder}/{fn}")
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.move(self.abs(rel), dst)
                    log(f"  archived stale note {rel}")

    # ---------------------------------------------------------- notes -> store
    def _resolve_link(self, v):
        m = re.search(r"\[\[([^\]|#]+)", str(v or ""))
        target = (m.group(1) if m else str(v or "")).strip()
        if not target:
            return None
        r = self.s.db.execute("SELECT id FROM entities WHERE note_path=? OR note_path=?",
                              (target + ".md", target)).fetchone()
        if r:
            return r[0]
        name = target.rsplit("/", 1)[-1]
        hits = self.s.find_by_name(name)
        if len(hits) == 1:
            return hits[0]
        if len(hits) > 1:
            log(f"  ! ambiguous link {v!r}; use the full note path")
            return None
        return self.s.upsert_entity("unknown", name, {"manual": norm_name(name)})

    def sync(self):
        """Pull hand edits back: entity `domain`/tags, and manual edge notes anywhere under HOOT/."""
        base = self.abs(self.root)
        n_ent = n_edge = 0
        for dirpath, _, files in os.walk(base):
            parts = os.path.relpath(dirpath, base).split(os.sep)
            if parts[0] in ("_Archive", "Templates"):
                continue
            for fn in files:
                if not fn.endswith(".md"):
                    continue
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, VAULT_DIR).replace(os.sep, "/")
                fm, _ = yamlish.split(open(full, encoding="utf-8").read())
                if fm.get("hoot") == "entity" and fm.get("canonical_id"):
                    r = self.s.db.execute("SELECT id FROM entities WHERE canonical_id=?", (fm["canonical_id"],)).fetchone()
                    if r:
                        dom = fm.get("domain") or []
                        dom = [dom] if isinstance(dom, str) else [str(x) for x in dom if x]
                        e = self.s.entity(r[0])
                        if (e["attrs"].get("domain") or []) != dom:
                            self.s.set_attr(r[0], "domain", dom)
                            n_ent += 1
                elif fm.get("hoot") == "edge" and (fm.get("origin") == "manual" or not fm.get("edge_id")):
                    rel_name = fm.get("relation")
                    src, dst = self._resolve_link(fm.get("from")), self._resolve_link(fm.get("to"))
                    if not (rel_name and src and dst):
                        log(f"  ! skipped {rel}: needs relation, from, to")
                        continue
                    if rel_name not in RELATIONS:
                        log(f"  note: {rel}: relation {rel_name!r} is not in the standard list (treated as soft, w=0.3)")
                    f = {k: fm.get(k) for k in ("qualifier", "start_date", "end_date", "percent", "amount", "currency",
                                                "source", "evidence_url", "filing_date")}
                    f["is_current"] = None if fm.get("is_current") is None else int(bool(fm["is_current"]))
                    for k in ("start_date", "end_date", "filing_date"):
                        if f[k] is not None:
                            f[k] = str(f[k])
                    eid = self.s.add_edge(src, dst, rel_name, origin="manual", **f)
                    self.s.db.execute("UPDATE edges SET note_path=?, origin='manual' WHERE id=?", (rel, eid))
                    n_edge += 1
        self.s.commit()
        log(f"sync: {n_ent} entity domain updates, {n_edge} manual edges imported")
